### ISSUE TITLE
Padding For Header Icons

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#10]
Not a big issue, but please add padding or a margin for both the HAMSA and HA logos on all non-home pages. So I suppose that would be on the header, _class '3cafca4c'

That seems to throw off the HA logo a bit, so you'll have to compensate.

We want an even 8px around each logo.

**Comment by soapdog** [comment]
Done!

![image](https://user-images.githubusercontent.com/23247/44538128-dc0f4300-a6d6-11e8-99b9-bf99640727fe.png)

 it will be shipped along with the other fixes. I'd rather bundle them all into one deploy if possible.
