### ISSUE TITLE
Go Back Button

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#15]
the 'Go Back' button should have some sort of vertical-align: middle; for it's text.

or just hard code it as <span class="_99da1d4a" style="padding-top:7px;">Go Back</span>

**Comment by JaiNatha** [comment]
Odd. The suggested code I wrote here didn't come through.

At this point I'm not even seeing a back button

**Comment by soapdog** [comment]
I've removed the go back button. On mobile there is a top button to go back. On desktop it is really not needed as the browser has a go back button, also it looked kinda lost in the UI.

**Comment by soapdog** [comment]
@JaiNatha do we really need a _go back_ button there on the desktop? I feel it is an anti-pattern.
