### ISSUE TITLE
Art Tags - Styling

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#16]
On an art detail page, it shows all the tags.
They need to be styled like this:

._e274e9e3 {
    border-radius: 8px;
    cursor: pointer;
    background-color: #f1f6fffc;
    border: 1px solid #9a9a9a;
    margin-left: 3px;
    margin-right: 3px;
    padding: 5px;
    display: inline-block;
    color: #444;
    font-size: 12px;
}

**Comment by soapdog** [comment]
Done!

![image](https://user-images.githubusercontent.com/23247/44538693-7f148c80-a6d8-11e8-83a7-52e319a8a07d.png)
