### ISSUE TITLE
Download Button for Images

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#18]
We want to add a "Download Full-Size Image" button to the item view pages.

Something simple between the image and the <p> div below it. This would download the original full sized image.

If this starts to really slow down our server, we can remove this option later and have the download button fetch a smaller version.

**Comment by soapdog** [comment]
Done!

![image](https://user-images.githubusercontent.com/23247/44540021-0ca5ab80-a6dc-11e8-94e5-300f05d72305.png)
