### ISSUE TITLE
Mobile Nav - Search 

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#22]
We would like Search to appear on the first level of the mobile nav

Home
Tags
Artists
Collections
**Search**

**Comment by JaiNatha** [comment]
Not sure how this is going, but if it's easier for you, we have the option of putting it on the home page. Let me mock that up for you.

**Comment by JaiNatha** [comment]
![screen shot 2018-08-23 at 9 56 23 am](https://user-images.githubusercontent.com/25754228/44548801-d3a90f00-a6ba-11e8-8e85-26f54fb6fb84.png)

**Comment by JaiNatha** [comment]
This would actually be preferred. But if you're already far along on the nav-menu version, then don't worry about it.

**Comment by soapdog** [comment]
Done!

![image](https://user-images.githubusercontent.com/23247/44560354-b65d5a80-a725-11e8-9616-b9fc95413d73.png)

**Comment by soapdog** [comment]
it is live on the site.
