### ISSUE TITLE
Text visibility

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#23]
Grey text in art description and Artist, needs to be darker. Let's say #333333
Also anywhere else where there is a #919191 on top of white. 

Example:

<img width="818" alt="screen shot 2018-08-21 at 11 28 29 am" src="https://user-images.githubusercontent.com/25754228/44430206-ad0d9b80-a535-11e8-8e41-8e9e21dcc2a3.png">
<img width="1450" alt="screen shot 2018-08-21 at 11 28 37 am" src="https://user-images.githubusercontent.com/25754228/44430209-aed75f00-a535-11e8-877f-536a5ff3acaf.png">

**Comment by soapdog** [comment]
Fixed!

**Comment by JaiNatha** [comment]
Also needs to change for artist bios 
#333

**Comment by soapdog** [comment]
Fixed, will deploy it soon, there are other changes in progress that I need to finish before I can push this.

**Comment by soapdog** [comment]
pushed!

**Comment by JaiNatha** [comment]
Could you do this for the artist's name as well?

**Comment by soapdog** [comment]
done

**Comment by soapdog** [comment]
it is now live
