### ISSUE TITLE
Addition of intorduction blurb on Homepage

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#24]
Between div.hero and div.selector-controls add a section for a block of text (doesn’t have to appear on mobile). Sadasivanatha with provide the text to me soon. It’s kind of an intro text so people know what they’re looking at.

**Comment by JaiNatha** [comment]
Hold off on this one.

I think we're still looking at just how we want it to look.

**Comment by soapdog** [comment]
Ok!

**Comment by soapdog** [comment]
@JaiNatha lightboxes are a bit more involved. I will do this after finishing the other issues.

**Comment by JaiNatha** [comment]
Sounds good

**Comment by soapdog** [comment]
@JaiNatha I've added this as a new page. Please check it out, it is live.

**Comment by JaiNatha** [comment]
Looks good Andre
