### ISSUE TITLE
Download Button - STYLE

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#26]
Nice work, but could add a similar styling as the tags so it looks like a button.

style it thusly:
    cursor: pointer;
    background-color: #649800;
    border-radius: 8px;
    border: 1px solid #b7872b;
    margin-left: 3px;
    margin-right: 3px;
    padding: 5px;
    display: inline-block;
    color: #fff;
    font-size: 12px;

Something like this, but it should have an onPress rather than link text so that the text isn't underlined. Or just make it a button.

![screen shot 2018-08-23 at 9 30 47 am](https://user-images.githubusercontent.com/25754228/44547614-6e9fea00-a6b7-11e8-94b4-f4ebaf9e438c.png)

**Comment by soapdog** [comment]
Done!

![image](https://user-images.githubusercontent.com/23247/44551295-1a1f5d80-a6fd-11e8-91f1-7d18830fa410.png)
