### ISSUE TITLE
Home screen initial Hero Animation

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#27]
Ok so, 

We would like the hero, to start with this blue image on initial load, and then fade to the hero art image.
Bascially the image shoud be there for a few seconds and then fade over o few seconds. or whatever you think looks best. 

I've sent you a few things on slack depending on how you're able to go about it. One is an svg, which would go over a background color of #005b9e. The other two are jpg options, which might be easier to implement. On has smaller text because I wasn't sure if it would run into the dropdown banner or not. 

![screen shot 2018-08-23 at 10 02 20 am](https://user-images.githubusercontent.com/25754228/44550344-9f841d00-a6bf-11e8-87d2-32346e380f93.png)

**Comment by soapdog** [comment]
![image](https://user-images.githubusercontent.com/23247/44551405-74202300-a6fd-11e8-836a-943cbf966b68.png)

I've used one of the JPG files and centered it. Then I added the same blue as a background color for the enclosing `<figure>`. 

I need to do some research on how to do this animation, I am quite clueless about it. Do you want to ship an early version without it?

**Comment by JaiNatha** [comment]
This is a fade in, but should work the same for a fade out. 
Maybe position it over the art image and then fade it out. 

But yes, I'll ask paramacharya about making it V2

**Comment by JaiNatha** [comment]
Also, if we don't have the the banner fade, we'd like the hero to be the artwork image

**Comment by soapdog** [comment]
Done! I made the animation, phew...

**Comment by soapdog** [comment]
It is live on the site but it might be cached for you, use CMD+SHIFT+R

**Comment by JaiNatha** [comment]
Thanks Andre, looks good except that the art image looks stretched. Or maybe that's just me. :/

Also would you be able to delete ElementById or something on the sacredness jpg, after the fade is done?

**Comment by JaiNatha** [comment]
Ok, it looks like the image just isn't resizing proportionally. When it's really big it stretches and when really small, it squishes.

**Comment by soapdog** [comment]
@JaiNatha I can't delete nodes in Elm, I would need a state change and then not render them.

Yes the image is not proportional, to solve that I need to know what you prefer:
* Have it at a fixed size and crop the excess with `overflow: hidden`
* Have it proportional with `width: 100%; height: auto` causing the height to change depending on the image?

**Comment by soapdog** [comment]
Personally, I'd like that we set a specific height for that image and then created custom heroes by cropping the image we want in photoshop/affinity to the desired height.

**Comment by JaiNatha** [comment]
Ok,

just send me the sizes

**Comment by JaiNatha** [comment]
How about width 800, height 370 

I think that's what the blue one is now

**Comment by JaiNatha** [comment]
Oh they're both already that size
800x370

but I guess height is all that's important here. So 370px work?

**Comment by soapdog** [comment]
@JaiNatha used some fixed sizes. Used fixed heights and overflows. I don't really like the result. It is better than what we had before, but it leads to an off-center image for the "sacredness" image because it is overflowing on mobile.

I wish we could simply set `width: 100%` and let the height change as needed but I do need a fixed height on `div.hero` because it has a relative width, so unless I set a fixed height, the masonry tiles will climb on top of it.

**Comment by soapdog** [comment]
@JaiNatha  Anyway, it is live, please check it out. I will resume on it tomorrow, it is after midnight here and I'r rather do CSS (not my strong suit) with a clear head.
