### ISSUE TITLE
Celebrate Andre's Awesomeness

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#28]
![giphy](https://user-images.githubusercontent.com/25754228/44550700-b6773f00-a6c0-11e8-9492-a34e4340d89e.gif)

It looks like we're juts about finished. I don't foresee adding anymore issues after what is already here. Thanks for all the great work Andre!

**Comment by soapdog** [comment]
auhauhahuahu we're almost done @JaiNatha ❤️
