### ISSUE TITLE
API server blocked when accessing the site over secure connection

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/hamsa#30]
# Objective
We should be able to access HAMSA using both _http_ and _https_.

# Problem
Currently the API server URL is hardcoded to _http_ which leads to it being blocked when we access the site over _https_.

**Comment by soapdog** [comment]
Full and beautiful green padlock 🔒 on the dev site, meaning that all connections are now secure.

![image](https://user-images.githubusercontent.com/23247/44675092-da5ebb80-aa05-11e8-859a-955274b21381.png)

I am now testing a (hidden, as in not linked from anywhere) deploy on the live site.

**Comment by soapdog** [comment]
HAMSA is working fine on the live/production site.

![image](https://user-images.githubusercontent.com/23247/44675336-991adb80-aa06-11e8-9d03-e89505b1c240.png)

I haven't linked it from the menu, so users can't yet access it but it is working well.

@JaiNatha @Brahmanathaswami, can we go live with it? As in change the link in the menu like we did for devhap?

**Comment by soapdog** [comment]
just broke hamsa, permission issue... fixing.

**Comment by soapdog** [comment]
working now. Steps to solve:

* Create a new group on the server called `hamsa`.
* Added _root, himalayan, devhap_ to this group.
* Changed `/mnt/ExtraStorage1/hamsa/images` to be owned by `hamsa` group.
* Added `+FollowSymlinks` and **REMOVED** `+SymlinksIfOwnerMatches` from _himalayanacademy.com:443_ configuration.

**Comment by JaiNatha** [comment]
Aloha Andre,

Yes we can link it and go live once you’ve solved everything. 

Congratulations!
