### ISSUE TITLE
Bug in manivelu collection

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#31]
https://www.himalayanacademy.com/hamsa/#/categories/Collection%20Living%20With%20Siva

For some reason the loading stops after the "forgiveness.jpg" piece of art. Not sure why.

**Comment by soapdog** [comment]
@JaiNatha the link you passed is for the Living with Siva collection. For me it loads the following images:

![image](https://user-images.githubusercontent.com/23247/45977644-22dbba00-c042-11e8-80be-540edea823d4.png)

The collection for Manivelu loads these images for me:

![image](https://user-images.githubusercontent.com/23247/45977778-71895400-c042-11e8-92cc-b6a7dcfff3cd.png)

Don't know if this is correct but appears correct to me. We might need to arrange a call for us to do some screen share and see what is happening over there.

**Comment by soapdog** [comment]
humm my screenshots didn't work, it is probably the virtual dom just rendering the visible part. Anyway, it is loading a lot of images here.

**Comment by JaiNatha** [comment]
Screenshots work.

You notice how they both end with the same image?

As far as I can tell these collections aren't showing the full collection but stopping with whatever images is trying to load after this last visible one.

**Comment by soapdog** [comment]
Just double checked:

* The "Living With Siva" collection has 58 images in it and the 58 are loading.
* The "A. Manivelu" artist has 126 images and all the 126 images are loading.

@JaiNatha

**Comment by JaiNatha** [comment]
Right. I'm actually seeing 59 in the files, but there might be a duplicate.

**Comment by soapdog** [comment]
Is this still a problem?

**Comment by JaiNatha** [comment]
I think it's ok yes.
