### ISSUE TITLE
Add Aums from the /media/art folder both b/w and color

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#32]

**Comment by soapdog** [comment]
@JaiNatha is doing some AUMs collection. I don't know if they are the same Aums, but this should be coordinated with him as he is the person handling content.

**Comment by JaiNatha** [comment]
Yes, all Aums are already on HAMSA.

**Comment by soapdog** [comment]
Closing this task because it is already done.
