### ISSUE TITLE
Create a botton to download EPS version (without display)

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#33]
For all the art that we do in illustrator we want to get using the vector art. This simplest way to do this is save to generic EPS. We not have to display this, to it is not necessary to create SVG. But these should be a downloads but it and EPS version is available.

**Comment by soapdog** [comment]
We don't have the EPS files on HAMSA, all we have are JPEG files because the whole system is based in extracting data from EXIF/IPTC. There is no way for me to accomplish this task.
