### ISSUE TITLE
Get metadata from the old dbase for AUMs and insert into IPTC Core (

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#34]

**Comment by Brahmanathaswami** [comment]
All of the aums were given rational titles. We need to move this into the IPTO Core/Title field , there are some tag that may be userful also

**Comment by soapdog** [comment]
@JaiNatha is handling the content for HAMSA, I've seen him uploading an Aum collection, don't know if this are the same files. I am not the one doing content curation, I think this needs to go through him.

**Comment by JaiNatha** [comment]
The aums I uploaded should be this same collection. If you want the rational titles added you'll have to download the aum folder from the HAMSA storage on the server then programmatically insert the IPTC data and then re upload the folder. Unless you have a way of doing that without downloading them of course.. this is not an area I'm familiar with.

**Comment by soapdog** [comment]
This will require hours to get it right and still might get some bad cases. Do we want to proceed with this? @JaiNatha @Brahmanathaswami

**Comment by soapdog** [comment]
This issue is basically the same as #35 which is to pick data from jnanan and try to reconcile with hamsa. Do we feel it is time to do it?

**Comment by JaiNatha** [comment]
I'd say we should not proceed with this yet. I'll be sending you more work for the Virtual Tour today, something from Paramacharya that he wants to see done as priority.
