### ISSUE TITLE
Examine Previous Rajam and Manivelu Art mySQL Dbase, Move data to IPTC Core

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#35]
Rajan and Manivelu are were previous Title and Tagged by Gayatri Rajan, we should move the data to IPTC Core

**Comment by soapdog** [comment]
That should be handled by those doing the metadata tagging. I can't reconcile the data we have on the database with the files I have on HAMSA, they are not from the same source or have the same names. There are people doing the metadata tagging but that is not me, I can't really do this task, this should be handled by the metadata tagging team.

**Comment by Brahmanathaswami** [comment]
@soapdog 
1) Many do have the same names (all the aums)
2) there must be some way the promatically append metadata to the existing IPTC core data.

We can talk about it.

**Comment by soapdog** [comment]
We've talked about this in a skype call. Should we close this task? It is not actionable right now. @Brahmanathaswami
