### ISSUE TITLE
Create an interface for changing the metadata of images

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#40]
- [x] Need to have an ACL that is admin by us 
- [x] Using need to filter for artist, keyword, tag, name of the file etc. any of the IPTC data 
- [x] Using can change to the data..
- [x]  Consider using a global process that allows for changing mutiple tag in ITPC, be 
- [x] constrain the user to N number of images that can you processed before apache kills the process,  For example change "Siva" to "Siva, Shiva" in 50 records, not more.

**Comment by soapdog** [comment]
@Brahmanathaswami and @JaiNatha I think that before I start on this project, you should talk because I am getting mixed messages.

**Comment by JaiNatha** [comment]
Decision was that we'd need a quote that covers the rebuild and the Metadata interface before moving forward

**Comment by Brahmanathaswami** [comment]
Wrong Use of GIT -- please ignore/don't respond the above here. Sadasivanathaswami asked me to talk you with about it, look for me a SKYPE

**Comment by soapdog** [comment]
Just uploaded a new version which can be used to edit the following data from an image:

* caption (not used in HAMSA but available through GraphQL queries)
* description
* tags (aka keywords)
* collections

**Comment by Brahmanathaswami** [comment]
Excellent, I add that thing we talked about as discrete task, one by one.

**Comment by soapdog** [comment]
done.
