### ISSUE TITLE
Admin UI: add an place to add "Collection:Tag"

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#47]
We need to enter the collection from an ENUM list of collection, It would be the same as the menu, only at admin can add to the list. Then we the "Collection editor" goes out toe select image, she can choose for the list. This will save us for "data validation" and make sure they spelled correctly.

**Comment by soapdog** [comment]
To be able to an an image in a collection has already been implemented.

![image](https://user-images.githubusercontent.com/23247/73735925-e345d780-4737-11ea-9d1d-572d97c18624.png)

I'm still going to add a way for admins to add new collections but be aware that adding a tag that starts with `Collection ` creates a new collection.

**Comment by Brahmanathaswami** [comment]
Yes, We know that to add a collection just means a tag beginning with "Collection" But we want to try to avoid having to type it in "ad hoc" because a) more time b) inevitably there will be spelling errors

Which reminds me..... what happens if we find a tag that is misspelled that need corrections

**Comment by soapdog** [comment]
The Collection Editor that appears when you select multiple images can do that.
