### ISSUE TITLE
Add artists bio

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/hamsa#5]
# Objective

Each artist on the database can have a corresponding artist bio file. We need to make sure they are all available.

**Comment by soapdog** [comment]
Arumuga Manivelu: Born in 1941 at Nagapattinam in Tamil Nadu, A Manivelu learned art as a child from his father SN Arumuga Achari, who was a temple builder, a muralist and maker of temple chariots and iconic statues. Manivelu is widely known for his detailed paintings of gods, goddesses and various deities. He has painted the murthis of most South Indian temple deities, which are sold in temple stalls since photos are not permitted. For decades he completed hundreds of sacred and cultural images for Himalayan Academy publications, notably the many paintings in Living with Siva and Merging with Siva. He visited Kauai to paint the Kadavul Temple Nataraja. The artist lives in Chennai where he leads a simple life with his family, painting in his home-based studio.



Sundaram Rajam: (10 February 1919 – 29 January 2010) was an Indian actor, painter and Carnatic musician from the state of Tamil Nadu. He is known for his series of portraits of the Trinity of Carnatic music. In the 1990s Himalayan Academy purchased his lifetime of work, some 500 paintings, brought them to Kauai and digitized everything to preserve this amazing spiritual resource. Then for almost 20 years he painted the covers of all our books, a series for The Vedic Experience, Tirukural, sacred symbols and from 2002-2004 the precious illustrations for The Guru Chronicles.



Indra Sharma: Indra Sharma (1923 – 2006) of Kurawad in Rajasthan was a cousin of B.G. Sharma, both of whom worked in the Nathdwara art tradition. The artist’s ability to produce sublime images of saints and deities set against beautiful surroundings won him much critical acclaim. Exhibited in numerous exhibitions and illustrated in publications, his work is part of many private and public collections in India and worldwide. He visited his daughter on Kauai often, and ultimately painted several major portraits of Gurudeva and Yogaswami. His family still visits the monastery.



Suresh Muthukulam: When next you land at the new Mumbai airport, a massive 10' by 80' mural depicting flight will greet you, the work of S. Suresh Kumar, popularly known as Suresh Muthukulam. Traditionally trained and extraordinarily gifted, Suresh is arguably Kerala's leading muralist. Suresh was born in 1971 and mastered the Kerala mural tradition under an innovative gurukula system started by the Guruvayur Devaswom. In 1995 he became a visiting lecturer at the Ravi Varma Institute of Fine Arts. He painted nine masterpieces depicting Gurudeva’s visions, each four feet square.

I Wayan Marya: An acclaimed Balinese artist, I Wayan Marya spent two years painting the masterpieces that adorn the chapters of our book, The Lemurian Scrolls. He also painted Iraivan temple and an overview of the monastery property, capturing the lush magic of this land.



Pieter Weltevrede: Pieter Weltevrede began his artistic studies with the Indian master Harish Johari in 1977 and also studied with Shri Chandra Bal. He lives in Holland with his wife and three children and travels to India annually to teach art in the style of his guru. Pieter is a prolific artist and has collaborated with Himalayan Academy on numerous projects, including our Insights on the chakras and the mystic forms of Sadasiva.



Maniam Selvan: Maniam Selvan, (1950- ) is a leading illustrator in Tamil magazines living in Chennai. He was trained by his famous father, T.V. Subramaniam, known for his stylized watercolor work. Himalayan Academy has commissioned MaSe, as he signs his name, to do paintings of the life of Nimbarkacharya and a series on the nine rasas or human emotions.



N T Rajeev:   NT Rajeev is an Indian artist specializing in paintings for children. He has illustrated several of our books for youth and did a series for Hinduism Today for an Insight on ashtanga yoga for kids.

**Comment by soapdog** [comment]
Added Rajam and Manivelu

**Comment by soapdog** [comment]
I believe there might be some errors in the author field because I see the following artists available:

```
  "artists": [
      "S. Rajam",
      "",
      "Krause & Johansen",
      "Hinduism Today",
      "A. Manivelu"
    ]
  }
```

Which means that there are images with no author field and that some images are attributed to _Hinduism Today_ and _Krause & Johansen_.

**Comment by JaiNatha** [comment]
Maybe we can do something to ignore blanks, "Hinduism Today" and "Krause & Johnasen"

As for other artwork, I'm seeing the artist in the IPTC Core 'Creator' field, as well as in the Keywords: 
<img width="355" alt="screen shot 2018-08-12 at 10 36 34 am" src="https://user-images.githubusercontent.com/25754228/44006210-efced00e-9e1b-11e8-9d90-90f5243b0b4d.png">


Where is HAMSA looking for that data?

**Comment by soapdog** [comment]
@JaiNatha it is looking at those fields exactly. I am running the import script again, there was an error in it that was preventing new images form being imported as mentioned in #9 

I will add more ignore flags for:

>ignore blanks, "Hinduism Today" and "Krause & Johnasen"

**Comment by soapdog** [comment]
Done, will add bios now.

**Comment by soapdog** [comment]
@JaiNatha There is no photo for "I Wayan Marya", also right now there are only photos for:

```
 "Suresh Muthukulam",
      "I Wayan Marya",
      "S. Rajam",
      "Pieter Weltevrede",
      "A. Manivelu"
```

The others in this list are not present in the images collection.

**Comment by JaiNatha** [comment]
Can we do something hacky like "if there is no artist bio photo, then use artist's first piece of art as bio photo"

**Comment by soapdog** [comment]
@JaiNatha that would be trickier to do because it is hard coded, it basically picks the name of the artist, normalize it, and load from a known location. What I think I can do, is somehow add some JS that intercept broken images for that specific `<img>` and load a generic avatar, or hide it.

**Comment by soapdog** [comment]
I tried going this route, it is too complex for the problem we have. We just need to make sure we have images for our artists. If we don't, I will provide an empty image (1x1 blank pixel) we can use.

**Comment by soapdog** [comment]
Added a blank image for _I Wayan Marya_.
