### ISSUE TITLE
Website subtitle typo

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#50]
Should say “museum of spiritual art” not “arts”. No “s”

**Comment by soapdog** [comment]
fixed!

**Comment by JaiNatha** [comment]
Not seeing the fix on the live site. Still says "arts"

<img width="804" alt="Screen Shot 2020-02-13 at 10 33 18 AM" src="https://user-images.githubusercontent.com/25754228/74475827-43c9c880-4e4c-11ea-9022-fe15e9da234b.png">

**Comment by soapdog** [comment]
All the changes are only on devhap for the moment so that we update the live site all at once when we're happy with them.
