### ISSUE TITLE
Admin Editor: Captions and About This Image (and associated Metadata)

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#55]
- [ ] Caption: Make field taller
		Save to, same for all  (EXIF:ImageDescription; IPTC: Caption-Abstract; XMP:Description)
- [ ] Change "Description" to "About This Image" and make it small vertically 
- [ ] Save to Metadata "DocumentNotes"
- [ ] "About This Image" want to be seen by the public

**Comment by Brahmanathaswami** [comment]
![2020-02-07_03-54-45](https://user-images.githubusercontent.com/3675722/74035201-ed491f80-495d-11ea-8b34-d93336b90116.png)

**Comment by soapdog** [comment]
Replaced the routines for setting an image caption in the backend with routines to set image notes.

Now, the setImageDescription mutation will set `IPTC:Caption-Abstract, XMP:Description and EXIF:ImageDescription`. The setImageNotes will set `IPTC:DocumentNotes`

![image](https://user-images.githubusercontent.com/23247/74429184-6232c280-4e52-11ea-833b-c5ee7691fd03.png)

Working on the UI now.
