### ISSUE TITLE
Upload Data from Jnanam to HAMSA

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#57]
We need to have the same search capabilitles and MySQL for any  item in art, we should talk about this first

![2020-02-19_11-57-06](https://user-images.githubusercontent.com/3675722/74880524-80476980-530f-11ea-95ae-014bcb4975a7.png)

**Comment by soapdog** [comment]
Swami this task is not clear. Please be more descriptive of what is the outcome you want. I don't understand what you want to be done.

**Comment by soapdog** [comment]
This task is not actionable and HAMSA is transitioning to WP.
