### ISSUE TITLE
Change Work and Location on Admin UI

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#58]
As follows: Move collection to the top

Create and Assign Collection at the bottom
Interactive buttons look more like buttons
![2020-02-19_12-20-14](https://user-images.githubusercontent.com/3675722/74882645-8e978480-5313-11ea-8d2c-1ad78250b566.png)
 and not labels

**Comment by Brahmanathaswami** [comment]
On single image editing 
 [ ] eliminate the label "Add Tag"
 [ ] Change the button to something make it look like a button

![2020-02-19_12-39-24](https://user-images.githubusercontent.com/3675722/74883526-3bbecc80-5315-11ea-9010-8ada21f0513a.png)

**Comment by soapdog** [comment]
working on it

**Comment by soapdog** [comment]
will work on the button as asked for but just a disclaimer that that is a native macOS button, that is how buttons look now. I will style them to be more visible, I just wanted to be clear that that is an official macOS button with its default look.

**Comment by soapdog** [comment]
deployed a new version, it looks like this:

![image](https://user-images.githubusercontent.com/23247/75470018-e6736280-5987-11ea-8696-1a780de41c38.png)
