### ISSUE TITLE
Add more collections

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/hamsa#7]
# Objective 

Add more collections to the system.

# Remarks

The way collections work in the system is that one can add one or more _keyword_ metadata to the EXIF data in the image in the form of `Collection <Collection Name>` such as `Collection Merging With Siva`. 

This is not folder based, we just need to add _collection tags_ to the images to add more collections.

**Comment by JaiNatha** [comment]
Ok Andre,

I'll go through the Art and do some collection tagging

**Comment by JaiNatha** [comment]
I've added a few. Looks like it needs a rebuild or something for them to show up.

**Comment by soapdog** [comment]
There was an error in the import script. I've just fixed it and am running it again.

**Comment by soapdog** [comment]
Collections are now working
