### ISSUE TITLE
Addition of remaining Artists to "artists" dropdown

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#9]
The "Artists" dropdown currently only displays 4 artists. Nearly all the art is uploaded, so we should be seeing Pieter Weltevrede, Suresh Muthukalam, Indra Sharma, etc.

**Comment by soapdog** [comment]
I am working on it

**Comment by soapdog** [comment]
This is fixed. I am closing this in favor of #5
